name: test-job
on: [push]
jobs:
  test:
    runs-on: ['self-hosted']
    steps: 
      - run: |
              echo "Test!"
              echo "Hello,"
              echo "World!"
  test2:
    runs-on: ['self-hosted']
    steps:
      - run: echo "This is stage 2!"
  test3:
    runs-on: ['self-hosted']
    steps:
      - run: figlet "WELCOME" 
